config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  root to: "pages#home"
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get 'home', to: 'pages#home', as: :home

  get 'about', to: 'pages#about', as: :about

  get 'portfolio', to: 'pages#portfolio', as: :portfolio
  resources :projects do
  end

  get 'services', to: 'pages#services', as: :services

  get 'blog', to: 'pages#blog', as: :blog

  get 'contact', to: 'pages#contact', as: :contact

  # only by logged In # Pages available:

  get 'dashboard', to: 'pages#dashboard', as: :dashboard

  get 'messages', to: 'pages#messages', as: :messages

  get 'courses', to: 'pages#courses', as: :courses


  # :controllers => { :omniauth_callbacks => "callbacks" }
  # Defines the root path route ("/")
  # root "articles#index"
  # contactform - email:
  # resources :contacts, only: [:new, :create ]
  # get '/contacts', to: 'contacts#new', as: 'contact'
  get 'contacts/sent'
end

app/views/shared/_feed.html.erb
<h1 class='project-name'  style="margin-top: 50px">Feed</h1>
<div data-controller='search'>
  <div class="d-flex justify-content-center mb-3">
    <% Project::PROJECT_TAGS.each do |tag| %>
      <a type="button" tabindex="0" data-action='click->search#tag' class='badge badge-pill badge-light' data-search-target='tag' id="tag">

        <%= tag %>

      </a>
    <% end %>
  </div>
  <div class="feed-wrapper" onload="initEmptySearch()" data-search-target='list'>
    <% @projects.each do |project| %>
    <div class='card' style="width: auto;">
      <%= link_to project_path(project) do %>
        <% if project.photo.attached?  %>
          <div class="card-img-top phot" id="photo" style='position:relative;width:auto;height: 200px; overflow: hidden; background-size: cover;background-image: url("https://res.cloudinary.com/antshaw/image/upload/<%= project.photo.key%>")' data-photo-key="<%= project.photo.key%>" src="" alt="Card image cap">
          </div>
          <% else %>
          <div class="card-img-top" style='position:relative;width:auto;height: 200px; overflow: hidden; background-size: cover;background-image: url("/photos/<%= project.project_tag %>.jpg");' src="" alt="Card image cap">
        </div>

        <% end %>

      <div class="card-body">
        <div class="body-header d-flex justify-content-between align-items-center mb-3">
          <div class="col d-flex align-items-center">
            <% if project.user.photo.attached? %>
                <%= cl_image_tag project.user.photo.key, class: "avatar avatar-msg menu-icon" %>
              <% else %>
                <%= image_tag "https://i.pravatar.cc/150?img=#{project.id}", class: "avatar avatar-msg menu-icon avatar menu-icon"%>
              <% end %>
            <h5 class='username'><%= project.name %></h5>
            </div>
            <p class='stats'><i class="fas fa-clipboard-list"></i><%= project.tests.count %></p>
            <p class='stats'><i class="fas fa-clipboard-check"></i>
               <%= project.tests.where(is_finished: false).count %>
            </p>
        </div>
        <p class='card-text desc'><%= project.description %></p>
        </div>
      <% end %>
    </div>
   <% end %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon" data-controller="navbar" data-action="scroll@window->navbar#updateNavbar">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "wbclogo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
      <li class="nav-item">
          <%= link_to "Home", '/home', class: "nav-link nav-white" %>
      </li>
      <li class="nav-item">
          <%= link_to "About", '/about', class: "nav-link nav-white" %>
      </li>
      <li class="nav-item">
          <%= link_to "Portfolio", '/portfolio', class: "nav-link nav-white" %>
      </li>
      <li class="nav-item">
          <%= link_to "Services", '/services', class: "nav-link nav-white" %>
      </li>
      <li class="nav-item">
          <%= link_to "Blog", '/blog', class: "nav-link nav-white" %>
      </li>
       <li class="nav-item">
          <%= link_to "Contact", '/contact', class: "nav-link nav-white" %>
      </li>
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Dashboard", '/dashboard', class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", '/messages', class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Courses", '/courses', class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "default-user.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>